services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inverted-index-app
    ports:
      - "8080:8080"
      - "9010:9010"
    environment:
      - SOURCE_INPUT_PATH=/app/index_files
      - SPRING_AI_OLLAMA_BASE_URL=http://ollama:11434
      - JAVA_TOOL_OPTIONS=-Xmx8g -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.rmi.port=9010 -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=127.0.0.1
    volumes:
      - index-volume:/app/index_files
      - ./index_files:/app/index_files
    depends_on:
      - ollama
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.32.11
    container_name: ollama
    ports: ["11434:11434"]
    volumes:
      - ./model_files:/model_files
      - ollama_data:/root/.ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    entrypoint: ["/bin/sh", "/model_files/run_ollama.sh"]
    deploy:
      resources:
        reservations:
          devices:
          - driver: ${OLLAMA_GPU_DRIVER-nvidia}
            count: ${OLLAMA_GPU_COUNT-1}
            capabilities:
              - gpu
        limits:
          memory: 2G

  ollama-webui:
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: ollama-webui
    ports: ["3000:8080"]
    volumes:
      - ollama-webui:/app/backend/data
    deploy:
      resources:
        limits:
          memory: 500m
    depends_on:
      - ollama
    environment:
      - 'OLLAMA_API_BASE_URL=http://ollama:11434/api'
    restart: unless-stopped

volumes:
  ollama_data:
  ollama-webui:
  index-volume: