spring:
  application.name: inverted-index
  ai:
    ollama:
      init:
        pull-model-strategy: when_missing
      base-url: ${OLLAMA_URL:http://localhost:11434}
      chat:
        model: ${OLLAMA_MODEL:llama3.2:3b}
        temperature: 0.0


ollama:
  defaultPrompt: ollama/prompt.txt

source:
  input-path: index_files
